### ISSUE TITLE
Andrew Maier's picture is not correct

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#12]
When I filter for team members who are working on the Team API project, I see @andrewmaier 
<img width="284" alt="screen shot 2016-03-14 at 3 30 18 pm" src="https://cloud.githubusercontent.com/assets/100149/13762092/e9e1dafc-e9f9-11e5-956c-36771c923d8a.png">
but the picture is incorrect. See attached screenshot

**Comment by nickbristow** [comment]
https://github.com/18F/team-browser/pull/62
