### ISSUE TITLE
I can click on a team member preview and go to that team member's page

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#17]
So that I can navigate to team member page to see more details about that team member, I should be able to click on the team member in the Team Browser index page, and navigate to the team member's page

Acceptance criteria:
Given that I am an 18F employee
And I'm on the Team Browser homepage (team.18f.gov)
And there are team members listed
When I click on either the full name or image of the team member
Then I should navigate to the team member page (team.18f.gov/["name"])
And the page title should be "18F - `full_name`"
And I should see the team member's `full_name` on that page

**Comment by mtorres253** [comment]
This just needs the title of the team member page to be updated.

**Comment by andrewmaier** [comment]
Hey Michael, should I work with John on this?

**Comment by mtorres253** [comment]
Sure. Let me know @andrewmaier

**Comment by mtorres253** [comment]
Are you going to work on this @andrewmaier? Or should I take it?
