### ISSUE TITLE
I know when there are no results for my filter combination

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#29]
So that I know that the empty page is because nothing matched my filter request, rather than thinking it's a bug, I should see a message telling me that

Acceptance Criteria
Given that I'm an 18F employee
And there are no team members who have CHI as their location, and have listed Javascript as a skill
When I filter for team members in the Chicago Office (CHI) who are skilled in Javascript
I should see a message telling me that there are no matches to my request

**Comment by mtorres253** [comment]
@andrewmaier can you take a look at this? The pull request is failing tests. If you don't have time, let me know and we can reassign

**Comment by andrewmaier** [comment]
Don't have time :(
