### ISSUE TITLE
I can navigate to team browser

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#45]
So that I have a place to go to see information about all team members, and what they're working on, I should be able to navigate to a UI containing this information.

Acceptance Criteria
Given I am an 18F employee
When I navigate to team.18f.gov in my browser
Then I should see the Team Browser homepage 
And the page title should be "18f - Team Browser"

**Comment by andrewmaier** [comment]
I'm not sure I'm the right person to do this?

**Comment by mtorres253** [comment]
this depends on hub/568
