### ISSUE TITLE
I should see an photo of each team member on the Team Browser homepage

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#49]
So that I can quickly put a name to a face for every team member at 18F, if there is a photo of that team member on the 18f website, I should see that same photo next to their name on the Team Browser homepage

Acceptance criteria
Given I am an 18f employee
When I am on the Team Browser homepage (team.18f.gov)
And there are team members here https://team-api.18f.gov/api/team/
And photos exist for any of the team members on the 18f website https://18f.gsa.gov/team/
Then I should see the team member's photo next to their full name.

Timebox investigation to a couple of hours

**Comment by mtorres253** [comment]
FYI @nickbristow this is how images are currently handled on the 18f site: https://18f.slack.com/archives/beta-18f-site/p1459194840000089

**Comment by nickbristow** [comment]
https://github.com/18F/team-browser/pull/63/files
