### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#53]
- [x]  Remove total count of team members just above list of team members
- [x] Remove "Edit this page" button in footer
- [x] Remove filter button on team index page

**Comment by jbarnicle** [comment]
@mtorres253 - I think we can break this out a little bit.  The remove unused pages / update team.yml seem like they would be better off in their own issues - items 1,2 and 5 are more front end issues.  I am taking care of these.  Can you more issues 3 and 4 somewhere else?

**Comment by mtorres253** [comment]
Yes I'll do that

**Comment by mtorres253** [comment]
I'll take the last checkbox @jbarnicle
