### ISSUE TITLE
Search results page is styled

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#61]
The search results page is appearing as expected, but looks a little rough. @andrewmaier would you style it to match the search results of the handbook?

To see:
Go to https://pages.18f.gov/team-browser/
Search for "Sarah"
Hit "enter"

Expected behavior: 
Search page is styled like the handbook search results page (see below)

Actual behavior: 
It doesn't seem to be styled at all

**Comment by mtorres253** [comment]
<img width="1043" alt="screen shot 2016-03-28 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/100149/14093227/2c07ffc6-f501-11e5-8a90-48fa6e833805.png">

**Comment by mtorres253** [comment]
@jeremiak Do you think you could take on this one? Should be quick

**Comment by jeremiak** [comment]
@mtorres253 np, will pick it up now.

**Comment by andrewmaier** [comment]
@mtorres253 @jeremiak I was assuming this would search "in page" and wouldn't send people to a unique search results page.

**Comment by andrewmaier** [comment]
(That is, it's just a way of filtering the results on the current page)

**Comment by jeremiak** [comment]
Totally understand, @andrewmaier. I think the goal is to just get this mostly wrapped up so it can be launched. To achieve that goal, I just styled the existing search results page to mostly match the style of the site.

For the next iteration, I think we should talk about refactoring the CSS from this project and [the handbook](/18f/handbook) to develop a shared style guide a la [fec-style](/18f/fec-style) or [cg-style](/18f/cg-style)
