### ISSUE TITLE
I can go to the edit page for a team member's yml file

### ISSUE THREAD

**Issue by mtorres253** [18F/team-browser#67]
As an 18f employee, I will want an easy way to get to my .yml file so that I can update/edit it and file a pull request. So there should be some way for me to do this via the UI

Acceptance Criteria:
Given that I am an 18f employee
When I'm viewing my show page in the team browser
Then I should see a button labeled "Update this team member"
And when I click on that button
Then I should be taken to the edit view for my .yml file in the team API repo
And the file should be in edit mode in the `team-updates` branch

**Comment by ertzeid** [comment]
If all of these changes will go onto a separate branch to be reviewed before being merged (as discussed at planning meeting), be aware that having long-living merge branches can sometimes lead to trickier merges with master. I don't anticipate it being a problem in this case, but wanted to write down the process that my team followed when we were doing something similar.

When merging the merge branch into master we used this process:
1. Get most up-to-date versions of both `master` and `merge-branch` with `git pull`
2. Merge `master` into `merge-branch`: from the merge branch, `git merge master`.
   This step helped to ensure that, if there were problems with the merge, we could clean those up without blocking everyone who needed to merge to master (which was a team of ~30 people)
3. Once all merge conflicts are dealt with (which shouldn't be much of a problem if people are just editing their own .yml files), merge the merge branch into master: from master, `git merge merge-branch`. This should produce a fast-forward commit on master, as the merge branch will already be up-to-date with master.

Note that the merge branch, like Master, should NEVER be force-pushed. If a regular push doesn't work, fix the problem before pushing. Though, again, this probably won't come up if the merge branch is only being edited by people working within the GitHub UI.

This isn't to say that this MUST be the process! The merging master into the branch may have had something to do with the standard processes we used at that job to keep a relatively clean git log on master (I honestly can't remember). But if there are problems just merging directly into master from the merge branch, it's something to consider.
